# Stage 1: Build da aplicação com Maven e Java 21 usando imagem oficial
FROM maven:3.9.11-eclipse-temurin-21 AS build

WORKDIR /app

# Copia o arquivo de configuração do Maven
COPY pom.xml .

# Faz o download das dependências para cache
RUN mvn dependency:go-offline -B

# Copia o restante do código-fonte
COPY src ./src

# Realiza o build da aplicação
RUN mvn clean package -DskipTests

# Stage 2: Cria a imagem final
FROM eclipse-temurin:21-alpine-3.22

WORKDIR /app

# Copia o jar gerado no stage de build
COPY --from=build /app/target/*.jar app.jar

RUN adduser -D app_user \
    && chown -R app_user:app_user /app \
    && chmod 500 app.jar

USER app_user

# Expõe a porta 8080
EXPOSE 8080

# Define o comando de execução da aplicação
ENTRYPOINT ["java", "-jar", "app.jar"]